Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,1 +1,35 @@
+name: Check Documentation
 
+on:
+  push:
+    branches:
+      - main
+
+  pull_request:
+    branches:
+      - main
+
+jobs:
+  check-docs:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Check docs folder
+        run: |
+         if [ ! -f "docs/ERD Diagram.png" ]; then
+         echo "ERD Diagram.png is missing!"
+          exit 1
+          fi
+
+           if [ ! -f "docs/Endpointplan.docx" ]; then
+           echo "EndpointPlan.docx is missing!"
+         exit 1
+         fi
+
+         if [ ! -f "docs/RaceDay.sql" ]; then
+         echo "RaceDay.sql is missing!"
+         exit 1
+         fi
